[project]
name = 'cosmic-nft'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cosmic]
path = 'contracts/cosmic.clar'
clarity_version = 2
epoch = 2.5


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
